header_message: 
  type: bool
  default: false
  description:
    en: 'Select to show message below header. Message sets a cookie when dismissed.'
message-color: 
  type: string
  default: "#FFF"
  description:
    en: 'Text color of the message. Default is White. The Background color is the Danger color from your palette'
